-- return {
-- 	'echasnovski/mini.deps', version='*',
-- 	config = function()
-- 		require('mini.deps').setup({
-- 			path = { package = path_package }
-- 		})
-- 	end
--
-- 		local add, later, now = MiniDeps.add, MiniDeps.later, MiniDeps.now
--
--
-- 		add({
-- 			source = 'yetone/avante.nvim',
-- 			monitor = 'main',
-- 			depends = {
-- 				'stevearc/dressing.nvim',
-- 				'nvim-lua/plenary.nvim',
-- 				'MunifTanjim/nui.nvim',
-- 				'echasnovski/mini.icons'
-- 			},
-- 			hooks = { post_checkout = function() vim.cmd('make') end }
-- 		})
-- 		--- optional
-- 		add({ source = 'hrsh7th/nvim-cmp' })
-- 		add({ source = 'zbirenbaum/copilot.lua' })
-- 		add({ source = 'HakonHarnes/img-clip.nvim' })
-- 		add({ source = 'MeanderingProgrammer/render-markdown.nvim' })
--
-- 		now(function() require('avante_lib').load() end)
-- 		later(function() require('render-markdown').setup({...}) end)
-- 		later(function()
-- 			require('img-clip').setup({...}) -- config img-clip
-- 			require("copilot").setup({...}) -- setup copilot to your liking
-- 			require("avante").setup({...}) -- config for avante.nvim
-- 		end)
--
-- }
